image: Visual Studio 2017
version: 2.5.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build:
- dotnet restore src\NanoIoC.sln
- .paket\paket.exe restore
for:
  - branches:
      only:
        - master
    after_test:
      - .paket\paket pack . --version %APPVEYOR_BUILD_VERSION%
  - branches:
      except:
        - master
    after_test:
      - .paket\paket pack . --version %APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_BRANCH%
artifacts:
  - path: '*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: SwvNoxiHqrSlHIyaWa3pnIu3O+1S19u16TXoTEuCTt4f0HPUCqAgsFr5bHEDVqyo
  on:
    branch:
      - master

